# Generated by Django 3.2.16 on 2022-11-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pre_transaction_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='income',
            field=models.IntegerField(null=True),
        ),
    ]
