# Generated by Django 3.2.16 on 2022-11-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221107_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense',
            field=models.IntegerField(null=True),
        ),
    ]
