# Generated by Django 3.2.16 on 2022-11-09 02:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221109_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pre_transaction',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='core.pre_transaction'),
            preserve_default=False,
        ),
    ]
