# Generated by Django 3.2.16 on 2022-11-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_transaction_pre_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pre_transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='pre_transaction',
            field=models.ManyToManyField(to='core.Pre_transaction'),
        ),
    ]
