# Generated by Django 3.2.16 on 2022-11-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20221109_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pre_transaction',
        ),
    ]
